#! /bin/bash

# 内网PC 通过出口PC 做NAT 连通外网
# 参数{on|off}
# on 时开启；off 时关闭

ON=0
GATEWAY_LOCAL='172.31.3.254'
GATEWAY_ONLINE='172.31.3.157'

errExit() {
	case $1 in
		1)
			echo "ERROR: must be root"
			;;
		*)
			echo "USAGE: $0 on|off"
			;;
	esac

	exit
}

# 执行该脚本必须为root
if [ ${EUID} -ne 0 ]; then
	errExit 1
fi

# 参数判断
if [ -z $1 ]; then
	errExit
fi

if [ $1 = "off" ]; then
	ON=0
elif [ $1 = "on" ]; then
	ON=1
else
	errExit
fi

# 函数操作
if [ $ON -eq 1 ]; then
	route del default gw ${GATEWAY_LOCAL}
	route add default gw ${GATEWAY_ONLINE}
else
	route del default gw ${GATEWAY_ONLINE}
	route add default gw ${GATEWAY_LOCAL}
fi

# 设置DNS
echo "nameserver 114.114.114.114" > /etc/resolv.conf

