#!/usr/bin/expect

set LOGIN_IP [lindex $argv 0]

spawn zssh -p 1022 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no administrator@$LOGIN_IP

expect {
  "*password:" {
    send "passwd\r"
  }
  "*Are you sure you want to continue connecting*" {
    send "yes\r"
    expect "*password:" 
    send "passwd\r"
  }
}

expect "ac>"
send "switchtodebug\r"

expect "*password:"
send "passwd\r"

#expect "*>"
#send "cd /usr/local/web\r"

interact
