#!/usr/local/bin/expect

set LOGIN_IP [lindex $argv 0]

spawn zssh -p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no administrator@$LOGIN_IP

expect {
  "*password:" {
    send "XXXXXX\r"
  }
  "*Are you sure you want to continue connecting*" {
    send "yes\r"
    expect "*password:" 
    send "XXXXXX\r"
  }
}

expect "ac>"
send "switchtodebug\r"

expect "*password:"
send "XXXXXX\r"

interact
