#! /bin/bash

# 出口PC 设置NAT
# 参数为 on 时开启；其他情况下关闭。

IF=wlp2s0

IP=`ifconfig ${IF} | grep 'inet[^6]' | cut -c 14-24`

ON=0
if [ -z $1 ]; then
	ON=0;
else
	if [ $1 = "on" ]; then
		ON=1
	fi
fi

if [ ${ON} -eq 1 ]; then
	iptables -t nat -A POSTROUTING -s 172.31.3.136 -o ${IF} -j MASQUERADE
	echo 1 > /proc/sys/net/ipv4/ip_forward
else
	iptables -t nat -F
	echo 0 > /proc/sys/net/ipv4/ip_forward
fi

